### ISSUE TITLE
Fatal error w 3.5.2

### ISSUE THREAD

**Issue by GaganMedia** [dotpay/WooCommerce2#77]
Fatal error: Uncaught Error: Call to undefined function bcadd() in wp-content/plugins/woocommerce-dotpay/Dotpay/Payment.php:1003 Stack trace: #0 wp-content/plugins/woocommerce-dotpay/Dotpay/Payment.php(340): Dotpay_Payment->normalizeDecimalAmount('275.00') #1 wp-content/plugins/woocommerce-dotpay/form/standard.phtml(47): Dotpay_Payment->getAmountForWidget() #2 wp-content/plugins/woocommerce-dotpay/Gateway/Gateway.php(142): include('/www/loveme/www...') #3 wp-content/plugins/woocommerce/templates/checkout/payment-method.php(30): Gateway_Gateway->payment_fields() #4 wp-content/plugins/woocommerce/includes/wc-core-functions.php(344): include('/www/loveme/www...') #5 wp-content/plugins/woocommerce/templates/checkout/payment.php(30): wc_get_template('checkout/paymen...', Array) #6 wp-content/plugins/woocommerce/includes/wc-core-functions.php(344): include('/www/loveme/w in wp-content/plugins/woocommerce-dotpay/Dotpay/Payment.php on line 1003

jak wracam do 3.3.1 to działa ale zamówienia opłacone pokazuje jako anulowane :(

**Comment by wpawel** [comment]
Od wersji [v3.5.1](https://github.com/dotpay/WooCommerce2/blame/v3.5.1/Dotpay/Payment.php#L993) do prawidłowego działania wtyczki niezbędne jest posiadanie zainstalowanego modułu bcmath() w używanej wersji PHP na serwerze.
Można to naprawic instalując stosowne rozszerzanie, np Ubuntu:
`sudo apt-get install php-bcmath` 

_" ale zamówienia opłacone pokazuje jako anulowane :("_
Przyczyny mogą być różne - szczegóły takiego zamówienia. domeny proszę przesłać na tech@dotpay.pl, sprawdzą konfigurację i logi dla tego przypadku,
